version: "{build}"

skip_tags: true

environment:
  matrix:
    - FEATURE: HUGE
# disabled
#    - FEATURE: TINY
#    - FEATURE: SMALL
#    - FEATURE: NORMAL
#    - FEATURE: BIG

matrix:
  fast_finish: true

before_build:
  # Use Windows SDK 7.1 (= MSVC 2010)
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 /release'
  # Visual Studio 2015 compiler tools
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64'
  - 'set INCLUDE=%INCLUDE%C:\Program Files (x86)\Windows Kits\8.1\Include\um'

build_script:
  - ci/appveyor.bat

test_script:
  - cd src/testdir
    # Testing with MSVC gvim
  - path C:\Python35-x64;%PATH%
  - nmake -f Make_mvc.mak VIMPROG=..\gvim
  - nmake -f Make_mvc.mak clean
    # Testing with MSVC console version
  - nmake -f Make_mvc.mak VIMPROG=..\vim

# vim: sw=2 sts=2 et ts=8 sr
